title: Zander (Alexander) Otavka
description: Software Engineer & Blogger
baseurl: ""
url: "https://zanderotavka.com"

author:
  name: "Alexander Otavka"

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

title_separator: " | "
social:
  linkedin: alexander-otavka
  github: AlexanderOtavka
