title: Zander Otavka
description: Software Engineer & Blogger
baseurl: ""
url: "https://zanderotavka.com"

author:
  name: "Zander Otavka"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /blog/:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

social:
  linkedin: alexander-otavka
  github: AlexanderOtavka
